spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

logging:
  level:
    com.example.secureapi: DEBUG
    org.springframework.security: DEBUG
